// placeholder — overwritten by generator
export const siteConfig = {
  eventType: 'gathering',
  designPreset: 'elegant-gold',
  title: '함께해 주세요',
  titleEn: "You're Invited",
  subtitle: '소중한 자리에 초대합니다',
  subtitleEn: 'We warmly invite you to join us',
  heroImageUrl: '',
  gradientFrom: '#b8860b',
  gradientTo: '#d4a853',
  eventDate: '2026-06-15',
  eventTime: '14:00',
  eventDateLabel: '2026년 6월 15일 토요일 오후 2시',
  eventDateLabelEn: 'Saturday, June 15, 2026 at 2:00 PM',
  showCountdown: true,
  countdownStyle: 'flip' as 'flip' | 'simple',
  hostsTitle: '초대하는 사람',
  hostsTitleEn: 'Hosted by',
  hosts: [{ name: '홍길동', role: '주최', phone: '', avatarUrl: '' }],
  venueName: '',
  venueNameEn: '',
  venueAddress: '',
  venueAddressEn: '',
  kakaoMapUrl: '',
  naverMapUrl: '',
  parkingInfo: '',
  transitInfo: '',
  galleryImages: [] as string[],
  galleryColumns: 3,
  accountTitle: '마음 전하기',
  accountTitleEn: 'Send Your Wishes',
  accounts: [] as { label: string; bankName: string; accountNumber: string; holder: string; }[],
  kakaoPayUrl: '',
  contacts: [{ name: '홍길동', phone: '010-1234-5678', role: '주최자' }],
};
